//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BowntDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Applocation
    {
        public int Id { get; set; }
        public string AppName { get; set; }
        public string ImgAddress { get; set; }
        public int LanguageId { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string Conver { get; set; }
    
        public virtual tb_Language tb_Language { get; set; }
    }
}
